### ISSUE TITLE
tor-ctrl Tor control protocol violation (sending empty whitespace line)

### ISSUE THREAD

**Issue by adrelanos** [nyxnor/tor-ctrl#11]
I am not sure this is worth fixing. Not seeing any actual issues resulting from this.

When running tor-ctrl in Whonix-Workstation...

```
tor-ctrl -d signal NEWNYM
```

onion-grater in debug mode shows the following:

> Jan 15 20:45:18 host onion-grater[1759]: 10.138.33.155:40700 (filter: 30_autogenerated): ignoring received empty (or whitespace-only) line

([enabling onion-grater debugging](https://www.whonix.org/wiki/Dev/Control_Port_Filter_Proxy#onion-grater_enable_debug_mode))

**Comment by nyxnor** [comment]
It happened here:
```sh
+ socat TCP:127.0.0.1:9051+ cmd_pipe
+ send_cmd 
+ printf %s\n 
 -
+ sleep 0
```
and should not

**Comment by nyxnor** [comment]
tested now, this was solved by changing to netcat-openbsd
