### ISSUE TITLE
tor-ctrl-stream: add human mode

### ISSUE THREAD

**Issue by nyxnor** [nyxnor/tor-ctrl#19]
from https://github.com/nyxnor/tor-ctrl/issues/13#issuecomment-1016432749

Adrelanos said:
1.
_Suggestion:_
_* --human (default?): show a greeting message "INFO: tor-ctrl-stream subscribed to Tor event setevents-stream. As soon as streams are created, output will be shown Below. To exit, press ctrl + c."_
_* --machine: no additional explanations. This is to make the output easier to parse in scripts._

_Not sure this all fits. I am looking for some tool to monitor where Tor is connecting to for the purpose of finding out about unwanted connections (bad for privacy or even malware)._

2.
_tor-ctrl-stream as is is OK as is for its use case. It's console output should not be published such as in public forums by users since it contains their whole circuit from Tor entry guard, middle relay and exit relay._

_Could you please add a warning (only shown when not using --machine) that posting this contents online could de-anonymize users?_

3.
_The utility I am looking for is actually something that users can share online without risk. Not showing Tor entry/middle/exit. Only showing which IPs or onions Tor is connecting to. Then users could share this in public places, post logs without risk, report bugs about unwanted connections (privacy violations or malware). That isn't a good idea to mix into tor-ctrl-stream. A separate utility for that purpose would be cool._

------------

~~Option probably gonna be `-h` because `df` (disk free) uses it also.~~ `-h` should be for help, will be defined later.
1. Part one of it was made a draft, it is just an warning any way. But mode human and default have not been made yet.
2. Warnings on human about sharing private information such as streams should be done also.
3. I think this can be done with tor-ctrl-stream and with an option, do not check for circuit paths. But I need you to define better the format you want (the fields you desire in control-spec format https://gitweb.torproject.org/torspec.git/tree/control-spec.txt).

**Comment by nyxnor** [comment]
```
tor-ctrl-stream: info: subscribed to Tor stream events, as soon as streams are created, output will be shown below.
tor-ctrl-stream: warn: posting these contents online can deanonymize the tor client.
tor-ctrl-stream: info: resume with Ctrl+C, quit with Ctrl+\.
250 OK
250 OK
^\Quit
```

**Comment by nyxnor** [comment]
3. Only IP and onion hostname might not be enough because it does not show if it succeeded, the circuit number to look later, reason field.

**Comment by nyxnor** [comment]
> I am looking for some tool to monitor where Tor is connecting to for the purpose of finding out about unwanted connections (bad for privacy or even malware).

Maybe you want to continue saving all streams? this will fill the file indefinitely:
```
tor-ctrl-stream > ~/torstream.log &
```

**Comment by adrelanos** [comment]
> tor-ctrl-stream: info: resume with Ctrl+C, quit with Ctrl+\.

Resume with Ctrl+C?
Ctrl+C is commonly used to terminate applications. Resume would be confusing.

**Comment by nyxnor** [comment]
Resume means it would stop listening for streams and print the streams organized table.
Which other signal would you recommend?
The second interrupt signal will quit the script https://github.com/nyxnor/tor-ctrl/blob/ea1ddcd507f480113626563b129d47800065481c/usr/bin/tor-ctrl-stream#L26

**Comment by nyxnor** [comment]
On my part, I think it is completed, except point 3 which is related to hiding tor-ctrl-stream circuit path, which I will not mix with `human` `machine` mode, will open another issue for this.

After testing, let me know.

**Comment by nyxnor** [comment]
this issue is complete with private stream mode and human mode vs machine mode.
After testing, if not behaving as expected, open the issue again.
