### ISSUE TITLE
should we use bash capabilities if socket is tcp type?

### ISSUE THREAD

**Issue by nyxnor** [nyxnor/tor-ctrl#3]
https://www.andreafortuna.org/2021/03/06/some-useful-tips-about-dev-tcp/

```sh
exec 3<>/dev/tcp/127.0.0.1/9051
printf '%s\n%s\n' "PROTOCOLINFO" "QUIT" >&3
cat <&3
```

benefit is not depending on downloading nc, socat, telnet.

would need to check minimal bash version.

had some issues trying to implement in the current state of the script.

**Comment by adrelanos** [comment]
I guess it's good enough as is. More and more unix domain socket based anyhow. And nc isn't a bad dependency.

Before someone comes and makes a different feature request: "avoid bashisms and port to sh".

**Comment by nyxnor** [comment]
agree with both statements, having major networking tools available has been great enough and not connecting to unix sockets with bash is not good.
