### ISSUE TITLE
messages improvement

### ISSUE THREAD

**Issue by adrelanos** [nyxnor/tor-ctrl#31]
tor-ctrl-observer 

> tor-ctrl-observer: [info]: subscribed to Tor stream events, as soon as streams are created, output will be shown below.

Good.

> tor-ctrl: [notice] connecting to socket with command: nc -U /run/tor/control

Good.

> attempting to connect to

[1] attempting to connect to... To what? And did it succeed? I guess so. But still a bit confusing.

> stop listening with Ctrl+C

Maybe rather write
`To stop listening and show a summary, please Ctrl+C.`
?

User could further think, yeah, sure, with Ctrl+C I can exit this. Thanks for the tip. But instead, I could also just close the window. But that's wrong, the Ctrl+C will actually show additional information.

> connecting to socket with

connecting to socket with... With what? And did it succeed? I guess so. But still a bit confusing. Similar to [1].

**Comment by nyxnor** [comment]
> [1] attempting to connect to... To what? And did it succeed? I guess so. But still a bit confusing.
> connecting to socket with... With what? And did it succeed? I guess so. But still a bit confusing. Similar to [1].

this was a bug, being fixed


> Maybe rather write
> To stop listening and show a summary, please Ctrl+C.
> User could further think, yeah, sure, with Ctrl+C I can exit this. Thanks for the tip. But instead, I could also just close the window. But that's wrong, the Ctrl+C will actually show additional information.

Valid, implemented.

Thanks.
